<a href="https://colab.research.google.com/github/agungdaus/data-science-2026/blob/main/Pertemuan2_Agung_Firdaus_240401010258.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#info

---




```
NAMA  : AGUNG FIRDAUS

NIM   : 240401010258

KELAS : IF403
```





In [ ]:
data = [10, 20, 'Python', True, 3.14]
# Akses & slicing
print(data[0]) # → 10
print(data[-1]) # → 3.14 (dari belakang)
print(data[1:3]) # → [20, 'Python']
# Manipulasi
data.append(99) # tambah di akhir
data.insert(1, 55) # sisipkan di posisi 1
data.remove(20) # hapus nilai pertama = 20
# data.sort() # urutkan (jika tipe sama)

import numpy as np
# Dari list Python
a1D = np.array([1, 2, 3, 4, 5]) # 1D
a2D = np.array([[1,2,3],[4,5,6]]) # 2D
# Array dengan nilai inisial
zeros = np.zeros((3, 4)) # nol semua
ones = np.ones((2, 3)) # satu semua
eye = np.eye(4) # matriks identitas
full = np.full((2, 2), 7) # nilai konstan
# Sequence
arange = np.arange(0, 20, 2) # 0,2,4,...18
linsp = np.linspace(0, 1, 11) # 11 titik merata
# Array acak (reproducible)
rng = np.random.default_rng(seed=42)
rand_int = rng.integers(0, 100, (3, 4))
rand_flt = rng.normal(loc=0, scale=1, size=(100,))

a = np.array([1, 2, 3, 4, 5])
b = np.array([10, 20, 30, 40, 50])
print(a + b) # → [11 22 33 44 55]
print(a * b) # → [10 40 90 160 250]
print(a ** 2) # → [1 4 9 16 25]
# Universal functions (ufuncs)
np.sqrt(a) # akar kuadrat tiap elemen
np.exp(a) # eksponensial (e^x)
np.log(b) # logaritma natural
# Fungsi statistik
data = rng.normal(0, 1, 1000)
print(f'Mean: {np.mean(data):.4f}')
print(f'Std: {np.std(data):.4f}')
print(f'Min: {np.min(data):.4f}')
print(f'Max: {np.max(data):.4f}')
print(f'Q1: {np.percentile(data,25):.4f}')
print(f'Q3: {np.percentile(data,75):.4f}')


import pandas as pd
# Series dari list — index default 0,1,2...
s1 = pd.Series([85, 92, 78, 95, 88])
# Series dengan index kustom
nilai = pd.Series(
[85, 92, 78, 95],
index=['Alice','Bob','Caca','Dina']
)
print(nilai['Bob']) # → 92
print(nilai[nilai>80]) # filter
print(nilai.mean()) # → 87.5
print(nilai.describe()) # statistik lengkap


# Membuat DataFrame dari dictionary
data = {
'nama': ['Ali','Budi','Caca','Dina'],
'usia': [22, 25, 21, 23],
'kota': ['Jakarta','Bandung','Surabaya','Medan'],
'ipk': [3.8, 3.5, 3.9, 3.7]
}
df = pd.DataFrame(data)
# Informasi dasar
print(df.shape) # → (4, 4)
print(df.dtypes) # tipe data per kolom
print(df.columns) # nama-nama kolom

10
3.14
[20, 'Python']
[11 22 33 44 55]
[ 10  40  90 160 250]
[ 1  4  9 16 25]
Mean: -0.0163
Std: 1.0008
Min: -3.6484
Max: 3.1789
Q1: -0.6897
Q3: 0.6163
92
Alice    85
Bob      92
Dina     95
dtype: int64
87.5
count     4.000000
mean     87.500000
std       7.593857
min      78.000000
25%      83.250000
50%      88.500000
75%      92.750000
max      95.000000
dtype: float64
(4, 4)
nama     object
usia      int64
kota     object
ipk     float64
dtype: object
Index(['nama', 'usia', 'kota', 'ipk'], dtype='object')


In [ ]:


import pandas as pd
import numpy as np

URL = "https://raw.github.com/datasciencedojo/datasets/master/titanic.csv"
df = pd.read_csv(URL)
df[['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp', 'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked']]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C


In [ ]:
#Q1 Berapa jumlah baris dan kolom pada dataset Titanic? Kolom apa saja yang tersedia?
import pandas as pd
import numpy as np

URL = "https://raw.github.com/datasciencedojo/datasets/master/titanic.csv"
df = pd.read_csv(URL)

# Dimensi dataset
print(f"Baris : {df.shape[0]}")
print(f"Kolom : {df.shape[1]}")
print(f"\nKolom yang tersedia:\n{df.columns.tolist()}")

Baris : 891
Kolom : 12

Kolom yang tersedia:
['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp', 'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked']


In [ ]:
#Kolom mana saja yang memiliki missing values? Berapa jumlah dan proporsinya (%) per kolom?
# Hitung jumlah dan proporsi missing values
missing = df.isnull().sum()
missing_pct = (missing / len(df) * 100).round(2)

result = pd.DataFrame({
    'Missing': missing,
    'Proporsi (%)': missing_pct
})
print(result[result['Missing'] > 0])

          Missing  Proporsi (%)
Age           177         19.87
Cabin         687         77.10
Embarked        2          0.22


In [ ]:
#Q3 Berapa persen penumpang yang selamat (Survived=1)? Gunakan operasi NumPyatau Pandas.
# Menggunakan NumPy
survived_pct_np = np.mean(df['Survived'].values) * 100

print(f"[NumPy]  Selamat: {survived_pct_np:.2f}%")
print(f"Jumlah selamat : {df['Survived'].sum()} dari {len(df)} penumpang")

[NumPy]  Selamat: 38.38%
Jumlah selamat : 342 dari 891 penumpang


In [ ]:
#Q4 Filter penumpang wanita dari kelas 1 (Pclass=1). Berapa jumlahnya dan berapa rata-rata usianya?
# Filter: Sex == 'female' AND Pclass == 1
wanita_kelas1 = df[(df['Sex'] == 'female') & (df['Pclass'] == 1)]

jumlah = len(wanita_kelas1)
rata_usia = wanita_kelas1['Age'].mean()

print(f"Jumlah wanita kelas 1 : {jumlah}")
print(f"Rata-rata usia        : {rata_usia:.2f} tahun")

Jumlah wanita kelas 1 : 94
Rata-rata usia        : 34.61 tahun


In [ ]:
# Q5 Gunakan groupby untuk menghitung tingkat keselamatan (mean Survived) per kelas penumpang. Kelas mana yang paling tinggi?
# Groupby Pclass → mean Survived
survival_rate = df.groupby('Pclass')['Survived'].mean() * 100
survival_rate = survival_rate.round(2)

print(survival_rate)
print(f"\nKelas tertinggi: Kelas {survival_rate.idxmax()} ({survival_rate.max()}%)")

Pclass
1    62.96
2    47.28
3    24.24
Name: Survived, dtype: float64

Kelas tertinggi: Kelas 1 (62.96%)


In [ ]:
#Buat analisis tambahan berdasarkan variabel lain yang Anda anggap menarik.Sertakan interpretasi singkat.
# Analisis: tingkat keselamatan berdasarkan Sex × Pclass
pivot = df.pivot_table(
    values='Survived',
    index='Sex',
    columns='Pclass',
    aggfunc='mean'
) * 100

print(pivot.round(2))

# Bonus: survival berdasarkan embarkasi
embarked_surv = df.groupby('Embarked')['Survived'].mean() * 100
print("\nSurvival per embarkasi:\n", embarked_surv.round(2))

#Analisis silang Sex × Pclass mengungkap dampak kebijakan "women and children first" yang sangat jelas:
#wanita kelas 1 selamat hampir semua (96.81%), sementara pria kelas 2 hanya 15.74% — bahkan lebih rendah dari wanita kelas 3 (50%).

Pclass      1      2      3
Sex                        
female  96.81  92.11  50.00
male    36.89  15.74  13.54

Survival per embarkasi:
 Embarked
C    55.36
Q    38.96
S    33.70
Name: Survived, dtype: float64


#Kesimpulan
---

Para pertemuan kedua membahas tentang struktur data Python, NumPy, dan Pandas sebagai fondasi praktis manipulasi dan analisis data sepanjang mata kuliah.